export const data = {
  dates: {
    maximum: '2024-07-10',
    minimum: '2024-05-29',
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
      genre_ids: [16, 10751, 12, 35, 18],
      id: 1022789,
      original_language: 'en',
      original_title: 'Inside Out 2',
      overview:
        '13살이 된 라일리의 행복을 위해 매일 바쁘게 머릿속 감정 컨트롤 본부를 운영하는 ‘기쁨’, ‘슬픔’, ‘버럭’, ‘까칠’, ‘소심’. 그러던 어느 날, 낯선 감정인 ‘불안’, ‘당황’, ‘따분’, ‘부럽’이가 본부에 등장하고, 언제나 최악의 상황을 대비하며 제멋대로인 ‘불안’이와 기존 감정들은 계속 충돌한다. 결국 새로운 감정들에 의해 본부에서 쫓겨나게 된 기존 감정들은 다시 본부로 돌아가기 위해 위험천만한 모험을 시작하는데…',
      popularity: 7582.401,
      poster_path: '/pmemGuhr450DK8GiTT44mgwWCP7.jpg',
      release_date: '2024-06-11',
      title: '인사이드 아웃 2',
      video: false,
      vote_average: 7.729,
      vote_count: 1476,
    },
    {
      adult: false,
      backdrop_path: '/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg',
      genre_ids: [28, 12, 878],
      id: 786892,
      original_language: 'en',
      original_title: 'Furiosa: A Mad Max Saga',
      overview:
        '문명 붕괴 45년 후, 황폐해진 세상 속 누구에게도 알려지지 않은 풍요가 가득한 녹색의 땅에서 자란 퓨리오사는 바이커 군단의 폭군 디멘투스의 손에 모든 것을 잃고 만다. 가족도 행복도 모두 빼앗기고 세상에 홀로 내던져진 퓨리오사는 반드시 고향으로 돌아가겠다는 어머니와의 약속을 지키기 위해 인생 전부를 건 복수를 시작하는데...',
      popularity: 4274.109,
      poster_path: '/zaUFDdJidS4Nyyd6jb2Ok3Kq4Vo.jpg',
      release_date: '2024-05-22',
      title: '퓨리오사: 매드맥스 사가',
      video: false,
      vote_average: 7.707,
      vote_count: 1848,
    },
    {
      adult: false,
      backdrop_path: '/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg',
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: 'en',
      original_title: 'Despicable Me 4',
      overview:
        '슈트-업 하고 악당 전담 처리반 AVL이 된 에이전트 미니언즈와 미니언즈 만큼 귀여운 그루 주니어가 태어나면서 더욱 완벽해진 그루 패밀리. 이들 앞에 과거 그루의 고등학교 동창이자 그에게 체포당했던 빌런 맥심이 등장하고, 오직 그루를 향한 복수심에 불타올라 탈옥까지 감행한 맥심은 그루 패밀리의 뒤를 바짝 추격하며 위협을 가하기 시작하는데... 과연 에이전트 미니언즈와 그루 패밀리는 맥심을 막아낼 수 있을까?',
      popularity: 2915.161,
      poster_path: '/8BRSeREiz3UtDACuOjW8KyCyFuR.jpg',
      release_date: '2024-06-20',
      title: '슈퍼배드 4',
      video: false,
      vote_average: 8.012,
      vote_count: 122,
    },
    {
      adult: false,
      backdrop_path: '/gRApXuxWmO2forYTuTmcz5RaNUV.jpg',
      genre_ids: [28, 80, 53, 35],
      id: 573435,
      original_language: 'en',
      original_title: 'Bad Boys: Ride or Die',
      overview:
        '마이애미 강력반 최고의 콤비 마이크와 마커스. 가족 같은 하워드 반장이 사망 전 마약 카르텔 조직의 비리에 연루되었다는 뉴스 속보를 접하게 된다. 하지만 아무도 믿지 말라는 하워드 반장의 비밀 메시지를 받은 마이크와 마커스 형사는 사건의 진실을 밝히기 위해 위험한 수사를 시작한다. 서서히 드러나는 거대한 음모와 마주하게 된 나쁜 녀석들. 그러나 이들 역시 함정에 빠져 사건의 용의자로 지목되며 동료 경찰들은 물론 마약 카르텔 조직에게도 쫓기는 신세가 되고 마는데…',
      popularity: 1985.833,
      poster_path: '/wIrhEUBWjRmZuL1Ix41cF2LhJrW.jpg',
      release_date: '2024-06-05',
      title: '나쁜 녀석들: 라이드 오어 다이',
      video: false,
      vote_average: 7.037,
      vote_count: 504,
    },
    {
      adult: false,
      backdrop_path: '/5Aks5cCqHG8xFLoUSLsfGdVfIC.jpg',
      genre_ids: [14, 9648, 53],
      id: 1086747,
      original_language: 'en',
      original_title: 'The Watchers',
      overview:
        "거대한 숲 속 기이한 쉘터에 고립된 '미나'가 낯선 세명의 사람들과 함께 매일 밤 자신들을 지켜보는 미지의 존재들로부터 벗어나기 위한 사투를 그린 미스터리 공포",
      popularity: 1138.034,
      poster_path: '/vZVEUPychdvZLrTNwWErr9xZFmu.jpg',
      release_date: '2024-06-06',
      title: '더 워처스',
      video: false,
      vote_average: 6.566,
      vote_count: 408,
    },
    {
      adult: false,
      backdrop_path: '/iTWrsOVsUqcwYSxrpINNs3hG2nC.jpg',
      genre_ids: [53, 27, 28, 9648],
      id: 1001311,
      original_language: 'fr',
      original_title: 'Sous la Seine',
      overview:
        '국제 대회를 앞둔 파리의 센강에 거대한 상어가 나타난다. 유혈 사태를 막고자 소환되는 한 과학자. 당면한 문제를 해결하려면, 자신을 사로잡고 있는 과거의 비극부터 마주해야 한다.',
      popularity: 1333.225,
      poster_path: '/iqTyxjbtWImvdXysxqvLzTF2sHB.jpg',
      release_date: '2024-06-04',
      title: '센강 아래',
      video: false,
      vote_average: 6.053,
      vote_count: 842,
    },
    {
      adult: false,
      backdrop_path: '/aATi2PtaOQCVAquCym6OU0Z4FjY.jpg',
      genre_ids: [28, 80, 53],
      id: 704673,
      original_language: 'en',
      original_title: 'Trigger Warning',
      overview:
        '사랑하는 아버지의 죽음. 그 뒤에 숨은 비밀을 밝히기 위해 고향으로 돌아온 특수부대 요원이 위험한 음모를 파헤친다.',
      popularity: 1219.45,
      poster_path: '/cVKgkOu8WSpZ7xK0axzrEaDNvvZ.jpg',
      release_date: '2024-06-20',
      title: '트리거 워닝',
      video: false,
      vote_average: 5.8,
      vote_count: 273,
    },
    {
      adult: false,
      backdrop_path: '/upk042Tms2EBfIzJf13OtOej0sd.jpg',
      genre_ids: [10752, 28, 18],
      id: 929590,
      original_language: 'en',
      original_title: 'Civil War',
      overview:
        '이 영화는 뉴욕에서 워싱턴 D.C.로 여행하는 기자 팀을 따라가며, 권위주의 연방 정부와 여러 지역 파벌간에 미국 전역에서 벌어진 내전을 그린다. 이들 기자들은 반란군이 백악관을 전복하기 전에 워싱턴 D.C.에 도착하려고 노력한다. 이 영화는 전쟁에 대한 충격적이고 폭력적인 사건들을 탐구하면서 미래의 미국을 배경으로 한 언론 윤리에 대한 사색을 제공한다',
      popularity: 1197.279,
      poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
      release_date: '2024-04-10',
      title: '시빌 워',
      video: false,
      vote_average: 7.005,
      vote_count: 1822,
    },
    {
      adult: false,
      backdrop_path: '/6XjMwQTvnICBz6TguiDKkDVHvgS.jpg',
      genre_ids: [27, 878, 53],
      id: 762441,
      original_language: 'en',
      original_title: 'A Quiet Place: Day One',
      overview:
        "평균 소음 90 데시벨을 자랑하는 미국 최대도시 뉴욕, 고양이 프로도와 함께 간만에 외출을 나온 사미라는 공연을 보고 돌아가던 중 하늘에서 떨어져 내리는 섬광을 목격하고 곧 사람들을 닥치는 대로 공격하는 정체불명 괴생명체의 출현에 충격에 휩싸인다. 아수라장이 된 뉴욕 도심에 ‘절대 소리 내지 말라’는 안내방송이 울려퍼지는 가운데 맨해튼의 모든 다리가 폭격으로 끊어지고, 사람들은 온갖 위협이 도사리는 도시에 고립되고 만다. 살아남기 위해 홀로 사투를 벌이던 '사미라'는 우연히 또 다른 생존자 에릭을 만나고 두 사람은 괴생명체를 피해 지하철역부터 시가지, 할렘까지 숨죽인 여정을 이어 나가는데…",
      popularity: 1067.524,
      poster_path: '/eufjDFIHtFSmcblWpvw5BiNzmO6.jpg',
      release_date: '2024-06-26',
      title: '콰이어트 플레이스: 첫째 날',
      video: false,
      vote_average: 6.936,
      vote_count: 307,
    },
    {
      adult: false,
      backdrop_path: '/yHEFwHkU2NqRxBrAoGBfuhuqIL1.jpg',
      genre_ids: [35, 28],
      id: 1143019,
      original_language: 'fr',
      original_title: 'Les Infaillibles',
      overview: '',
      popularity: 1111.478,
      poster_path: '/jEjVWSz1hhVCO5Ab5QId90m6AfW.jpg',
      release_date: '2024-06-20',
      title: 'Les Infaillibles',
      video: false,
      vote_average: 5.885,
      vote_count: 39,
    },
    {
      adult: false,
      backdrop_path: '/c2Gd2QwQx7IITMUoJgcckqMniqd.jpg',
      genre_ids: [27, 18, 9648],
      id: 1020896,
      original_language: 'no',
      original_title: 'Håndtering av udøde',
      overview:
        "손자이자 아들이었던 ‘엘리아스’를 잃고 슬픔 속에 살아가던 아버지 ‘말러’와 딸 ‘안나’부터 반려자 ‘엘리자베트’의 장례식을 막 끝내고 텅 빈 집으로 돌아온 ‘토라’, 교통사고로 즉사한 아내 ‘에바’를 마주한 남편 ‘데이빗'까지. 세상을 떠났던 사랑하는 사람들이 하나둘 그들의 곁으로 돌아온다, 무덤에 묻혔던 모습 그대로!",
      popularity: 876.741,
      poster_path: '/yp2JCSJbMMpLXMy45dM2wtUi8hP.jpg',
      release_date: '2024-02-09',
      title: '언데드 다루는 법',
      video: false,
      vote_average: 6.429,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: '/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg',
      genre_ids: [28, 35, 80],
      id: 280180,
      original_language: 'en',
      original_title: 'Beverly Hills Cop: Axel F',
      overview:
        '잊지 못할 비버리 힐스에서의 첫 사건 후 어느덧 40년. 디트로이트 형사 액셀 폴리가 자신의 특기를 발휘하러 다시 돌아온다. 범죄를 해결하러, 물론 말썽도 일으키면서.',
      popularity: 610.561,
      poster_path: '/eiAeSJZiVrjytYSi0cdBTZCNA13.jpg',
      release_date: '2024-06-20',
      title: '비버리 힐스 캅: 액셀 F',
      video: false,
      vote_average: 7.037,
      vote_count: 324,
    },
    {
      adult: false,
      backdrop_path: '/w2zsNG7WKBMH35QqcFYILEAdYDU.jpg',
      genre_ids: [14, 12, 10751],
      id: 1026999,
      original_language: 'pl',
      original_title: 'Akademia Pana Kleksa',
      overview:
        '겉으로는 평범해 보이는 소녀. 실종된 아버지를 찾기 위해 특별한 학교에 입학하라는 초대를 수락하는데, 그곳은 클렉스라는 괴짜 선생님이 운영하는 마법 아카데미이다.',
      popularity: 688.555,
      poster_path: '/qhc04gCqRgajeB3iS1OG5cJIwgN.jpg',
      release_date: '2024-01-05',
      title: '클렉스 아카데미',
      video: false,
      vote_average: 6.333,
      vote_count: 57,
    },
    {
      adult: false,
      backdrop_path: '/nxxCPRGTzxUH8SFMrIsvMmdxHti.jpg',
      genre_ids: [35, 14, 10751],
      id: 639720,
      original_language: 'en',
      original_title: 'IF',
      overview:
        '상상의 친구 ‘이프’를 볼 수 있는 능력을 지닌 한 소녀가 아이들에게 잊혀졌던 ‘이프’를 다시 되찾아주기 위해 마법 같은 모험을 시작하는 이야기를 그린 영화',
      popularity: 687.04,
      poster_path: '/9GAOhSzXjXJR4AxYCa2AMzMGPVg.jpg',
      release_date: '2024-05-08',
      title: '이프: 상상의 친구',
      video: false,
      vote_average: 7.403,
      vote_count: 569,
    },
    {
      adult: false,
      backdrop_path: '/ngLxW9WqQAkTCBTcjOSt2Pnz5qZ.jpg',
      genre_ids: [10749, 35],
      id: 987686,
      original_language: 'en',
      original_title: 'A Family Affair',
      overview:
        '손 많이 가고 까칠한 데다 나를 제대로 인정해주지도 않는 스타 배우. 그 사람의 비서가 되는 것보다 더 끔찍한 일이 딱 하나 있다면? 바로 그 스타가 우리 엄마한테 반했다는 사실을 알게 되는 것.',
      popularity: 597.527,
      poster_path: '/dtXKuLOhhtWF9DycqL7LUPB2NPT.jpg',
      release_date: '2024-06-27',
      title: '가족이라서 문제입니다',
      video: false,
      vote_average: 6.07,
      vote_count: 244,
    },
    {
      adult: false,
      backdrop_path: '/h7V8yzSnPYkNEvAqmeYHcfJ6rbk.jpg',
      genre_ids: [27, 53],
      id: 1214509,
      original_language: 'en',
      original_title: 'In a Violent Nature',
      overview:
        '외딴 황야에서 언데드 몬스터의 신비로운 부활과 난동, 보복이 시작되고, 썩은 시체가 묻힌 무너진 불탑에서 로켓이 제거된 후 상징적인 새로운 살인마가 등장한다.',
      popularity: 797.22,
      poster_path: '/o5pcDZaA9Up0X612os34JNCRX6j.jpg',
      release_date: '2024-05-31',
      title: '인 어 바이올런트 네이처',
      video: false,
      vote_average: 5.926,
      vote_count: 61,
    },
    {
      adult: false,
      backdrop_path: '/oavbmL3iddJUmC8nQjL6bLHwAP4.jpg',
      genre_ids: [27],
      id: 719221,
      original_language: 'en',
      original_title: 'Tarot',
      overview:
        "한 무리의 친구들이 타로 카드 읽기의 가장 중요한 규칙인 '타인의 카드 덱을 사용하지 말라'는 것을 무모하게 어긴다. 이로 인해 저주받은 카드 안에 갇혀있던 악마가 풀려나오게 되고, 하나둘씩 운명과 마주치며 카드 읽기에서 예견된 미래로부터 벗어나기 위해 죽음과의 치열한 레이스를 펼치게 된다.",
      popularity: 715.364,
      poster_path: '/sS9ePS66VV2HMUPk4pyA5qAyhII.jpg',
      release_date: '2024-05-01',
      title: '타로',
      video: false,
      vote_average: 6.698,
      vote_count: 648,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [27],
      id: 1305928,
      original_language: 'en',
      original_title: 'The Cult',
      overview: '',
      popularity: 704.065,
      poster_path: '/mmDEyYd66Et6GsuB0Etj9ifQwTr.jpg',
      release_date: '2024-06-01',
      title: 'The Cult',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/vWzJDjLPmycnQ42IppEjMpIhrhc.jpg',
      genre_ids: [16, 35, 10751, 12],
      id: 748783,
      original_language: 'en',
      original_title: 'The Garfield Movie',
      overview:
        '세상귀찮 집냥이, 바쁘고 험난한 세상에 던져졌다! 집사 ‘존’과 반려견 ‘오디’를 기르며 평화로운 나날을 보내던 집냥이 ‘가필드’. 어느 날, 험악한 길냥이 무리에게 납치당해 냉혹한 거리로 던져진다. 돌봐주는 집사가 없는 집 밖 세상은 너무나도 정신없게 돌아가고 길에서 우연히 다시 만난 아빠 길냥이 ‘빅’은 오히려 ‘가필드’를 위기에 빠지게 하는데… 험난한 세상, 살아남아야 한다!',
      popularity: 542.419,
      poster_path: '/57g3pHYi3p0JNVO1LkcyYbeMDBf.jpg',
      release_date: '2024-04-30',
      title: '가필드 더 무비',
      video: false,
      vote_average: 6.819,
      vote_count: 199,
    },
    {
      adult: false,
      backdrop_path: '/SI22DaQXIfDvLrNBHGpSVShrsC.jpg',
      genre_ids: [16, 878, 10751, 28],
      id: 829402,
      original_language: 'en',
      original_title: 'Ultraman: Rising',
      overview:
        '아버지가 해 왔던 울트라맨 역할을 계승하기 위해 어쩔 수 없이 고국으로 돌아온 슈퍼스타 운동선수. 전설적인 히어로가 되어 거대 괴수로부터 도쿄를 지켜내야 하는데.',
      popularity: 465.535,
      poster_path: '/x5HWKGh0gqc7NygC6zn1VSSVlgD.jpg',
      release_date: '2024-06-14',
      title: '울트라맨: 라이징',
      video: false,
      vote_average: 8.409,
      vote_count: 175,
    },
  ],
  total_pages: 223,
  total_results: 4452,
};
